import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "../globals.css";
import HomeNavigationContainer from "./components/home-navigation-container";
import FooterContainer from "./components/footer-container";
import ProjectDiscussionContainer from "./components/project-discussion-form";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CA Website NextJS & Sanity",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // get all og our pages
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col bg-white relative">
          <HomeNavigationContainer />
          {children}
          <div className="lg:max-w[506px] ml-auto mr-auto -mb-32 relative z-10 lg:px-0 px-5">
            <ProjectDiscussionContainer />
          </div>          
          <FooterContainer />
        </div>
      </body>
    </html>
  );
}
