import { client } from '@/sanity/lib/client';
import { NextResponse } from 'next/server';
import nodemailer from 'nodemailer';

export async function POST(req: Request) {
  try {
    const body = await req.json();

    const lead = {
      _type: 'fbMetaLead',
      name: body.name,
      email: body.email,
      companyName: body.companyName,
      campaignName: body.campaignName,
      creationDate: body.creationDate,
      phoneNumber: body.phoneNumber,
      date: body.creationDate,
      bookingTime: body.bookingTime,
    };

    // Step 1: Save to Sanity
    await client.create(lead);

    // Step 2: Setup Nodemailer transporter
    const transporter = nodemailer.createTransport({
      service: 'Gmail',
      auth: {
        user: process.env.EMAIL_USER, // your Gmail address
        pass: process.env.EMAIL_PASS, // App password (not your Gmail login)
      },
    });

    const teamEmail = 'adnan@codeautomation.dev'; // Change to your team email
    const clientEmail = body.email;

    await transporter.sendMail({
      from: `"Meta Lead Bot" <${process.env.EMAIL_USER}>`,
      to: teamEmail,
      subject: '🚨 New FB Meta Lead Submitted',
      html: `
  <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: #f9f9f9; padding: 40px;">
    <table width="100%" style="max-width: 600px; margin: 0 auto; background: white; border-radius: 12px; box-shadow: 0 2px 12px rgba(0,0,0,0.1); overflow: hidden;">
      <tr>
        <td style="background: #1d4ed8; padding: 24px; text-align: center; color: white;">
          <h1 style="margin: 0; font-size: 24px;">🚀 New Meta Lead Captured</h1>
        </td>
      </tr>
      <tr>
        <td style="padding: 32px; color: #111827;">
          <p style="font-size: 16px; line-height: 1.6;">A new Facebook Meta lead has been submitted. Here are the details:</p>
          <table style="width: 100%; font-size: 16px; margin-top: 20px;">
            <tr>
              <td><strong>Name:</strong></td>
              <td>${body.name}</td>
            </tr>
            <tr>
              <td><strong>Email:</strong></td>
              <td>${body.email}</td>
            </tr>
            <tr>
              <td><strong>Phone:</strong></td>
              <td>${body.phoneNumber}</td>
            </tr>
            <tr>
              <td><strong>Company:</strong></td>
              <td>${body.companyName}</td>
            </tr>
            <tr>
              <td><strong>Campaign:</strong></td>
              <td>${body.campaignName}</td>
            </tr>
            <tr>
              <td><strong>Date:</strong></td>
              <td>${body.creationDate}</td>
            </tr>
          </table>
          <div style="margin-top: 30px; text-align: center;">
            <a href="https://codeautomation.sanity.studio/studio/structure/fbMetaLead" style="padding: 12px 24px; background: #1d4ed8; color: white; border-radius: 6px; text-decoration: none; display: inline-block;">
              View in Sanity CMS
            </a>
          </div>
        </td>
      </tr>
      <tr>
        <td style="background: #f3f4f6; padding: 16px; text-align: center; font-size: 12px; color: #6b7280;">
          This email was automatically generated by your Meta Lead Bot.
        </td>
      </tr>
    </table>
  </div>
  `,
    });


    // Step 4: Send Thank You email to client
    await transporter.sendMail({
      from: `"CodeAutomation" <${process.env.EMAIL_USER}>`,
      to: clientEmail,
      subject: 'Thank You for Contacting CodeAutomation!',
      html: `
  <div style="font-family: 'Segoe UI', Tahoma, sans-serif; background-color: #f4f4f4; padding: 40px 0;">
    <table width="100%" style="max-width: 600px; margin: 0 auto; background: #ffffff; border-radius: 12px; box-shadow: 0 4px 16px rgba(0,0,0,0.1); overflow: hidden;">
      <!-- Header -->
      <tr>
        <td style="background-color: #1d92fb; padding: 24px 40px; text-align: center;">
          <h1 style="color: #ffffff; font-size: 26px; margin: 0;">Thank You, ${body.name}!</h1>
        </td>
      </tr>

      <!-- Body -->
      <tr>
        <td style="padding: 32px 40px; color: #333;">
          <p style="font-size: 16px; line-height: 1.6; margin-bottom: 16px;">
            We appreciate you contacting <strong>CodeAutomation</strong>. Your inquiry has been received and our team will get in touch with you shortly.
          </p>
          <p style="font-size: 16px; line-height: 1.6; margin-bottom: 24px;">
            In the meantime, feel free to book a 1-on-1 meeting with us at your convenience using the link below.
          </p>

          <div style="text-align: center; margin: 30px 0;">
            <a href="https://calendly.com/adnanghaffar" style="padding: 14px 28px; background: #1d92fb; color: white; border-radius: 6px; text-decoration: none; font-weight: 600; font-size: 16px; display: inline-block;">
              📅 Book a Meeting
            </a>
          </div>

          <p style="margin-top: 40px; font-size: 14px; color: #555;">
            Have questions? Just reply to this email — we’re here to help!
          </p>
          <p style="font-size: 14px; margin-top: 8px;">
            Best regards,<br/>
            <strong>The CodeAutomation Team</strong>
          </p>
        </td>
      </tr>

      <!-- Footer -->
      <tr>
        <td style="background: #f7e022; padding: 20px; text-align: center;">
          <div style="margin-bottom: 10px;">
            <a href="https://www.facebook.com/Codeautomationai/" target="_blank" style="margin: 0 8px;">
              <img src="https://codeautomation.ai/facebook.png" alt="Facebook" width="24" />
            </a>
            <a href="https://www.instagram.com/codeautomation.ai/" target="_blank" style="margin: 0 8px;">
              <img src="https://codeautomation.ai/instagram.png" alt="Instagram" width="24" />
            </a>
            <a href="https://twitter.com/codeautomation" target="_blank" style="margin: 0 8px;">
              <img src="https://codeautomation.ai/twitter.png" alt="Twitter" width="24" />
            </a>
            <a href="https://www.linkedin.com/company/codeautomationai/" target="_blank" style="margin: 0 8px;">
              <img src="https://codeautomation.ai/linkedin.png" alt="LinkedIn" width="24" />
            </a>
          </div>
          <div style="font-size: 12px; color: #333;">
            &copy; ${new Date().getFullYear()} CodeAutomation.ai LLC. All Rights Reserved.<br/>
            <a href="https://codeautomation.ai" style="color: #1d92fb; text-decoration: none;">Visit our website</a>
          </div>
        </td>
      </tr>
    </table>
  </div>
  `,
    });



    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Error submitting lead or sending emails:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to process lead' },
      { status: 500 }
    );
  }
}
