import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Import Poppins font
const poppins = "https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Import Poppins font */}
        <link rel="stylesheet" href={poppins} />
        {/* Apply Inter font */}
      </head>
      <body style={{ fontFamily: "'Poppins', sans-serif" }}>{children}</body>
    </html>
  );
}



// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
